language: node_js

node_js:
- '8.9'
- node

before_script:
- npm run build

after_success:
- npm run coverage

deploy:
  provider: npm
  skip_cleanup: true
  email: contact@francoisvoron.com
  api_key:
    secure: WXL5NRGPVr6xrd2azYWr88OlFzfAoSw4a9sR6Qda3E7Mzenjn0ycnN9fQjwdQCZmh5MyYr1LkQRdD3Y6JtybE6+hK2JrnG+osUFwHbfqIIxUkCTKEfGxXpj4eZg/RQ3FnI1kYbodks2/kJH5NKSOX3J69vpPpx/PLkFxAU6WlBkcBnA40DiKgu3S/zV3ZZlyRGi/6XdLBAi5p5y9+xSAN1npYftmi30SBEjic1nPqbdttXHYwzoAzhnzQZGTbjnKdGIiKE7iFHYxVMEzOiuIGs8taFBT93usTTL/L1RypgYfoduSoa+W0pI299Gacvsvh8n5AJU80QaFnpNnn35qkmspWlY6n74vaSkMaGm7jJj6lFd2O/0utzSzfO/8FjFUmN804CF/SI5oR7e4MKHqV3/27bD7SH2oVnKOYWK7C4Zr/yBG5viWsiTc9uuV1ypmmD/XkFtoKWAAghcvURYRQO+BC2f8mw7eyr0i41MAAAA5UF8WM1nhUBwFYLFeSPDnW3WnoJDejmSGSExmVixep9bRUzI2f/xwFGhJ3eNhnjv4n7MMvpraRHkSGAdbofuIBGRaffRNH0NqqIoWwCqrdv/akVmI1UITk/mVbh91idSSxYv3LxgdzVO8S3irGnYzyqB83w+6JYABAVkphCEk4ATuFfYus+/Jy1caFROkTsw=
  on:
    tags: true
    repo: wuha-team/slack-secret-middleware
