language: node_js

before_script:
- npm run build

after_success:
- npm run coverage

deploy:
  provider: npm
  on:
    tags: true
  api_key:
    secure: YnzgJONj7MH/fk2WaqRi47g0KEFkh7ylQNaFLbILGfx69j9LEM8ay1Rk4F8dkeU3Ke0coczUFnlINtpJIrOUmZS6pDz4pzYipWoRoVGwKd16udrQmfbps/izXD73XX4WcGfT/54H57YZJbLCBWlekcXc9Vvul4LKBLm/A2Y1uRFVdeWFs9Zn0ai/tw73aqsf2JwK49GLmQ6317grkSq0imtJC8boWvoItDFB6v3YAaNMAKFeqYoMarMDzOBTGt3X96wmsunRrEs/fz8KIKjRYg/QoCj3cUaATUlYH456UN71BhZ0IRHQ0MdfdPps4ddUGsa5aSnml075qr2sb55jt6FKrqNQI6ykTmvq5Y5uQbDDHt6yd4xsesgc4bvAc3iotNo147+GRxjJwU8/vYfrZNP4pTgM08tHEMwdk3W9uLZdkbD+zbJFVpSOmMgUkfjWFcnRx2kBoZch1ALZt8p4kTJu0y6HxHuDA2JpQpz2FvDC8vRDKGTLLx5cIfHhxFxgjuUT+NvOb1haFSx+7dvdQ64rUSp+I/iGPTsmfTqEHYnGXw/UOsRVgWZ8lpXmu3KT4H3nuH6SEX8sbumP1gk1H0N0oICR3PAlgPH+7Dkus/D4z/336DEAzfmFOXzD4oX0QfVCyyyF+iDB6G4/9EFXvxuhR7cX+dvEmRHIsLdceQk=
